version: '3.7'

services:
  czsc-stremlit_1:
    image: czsc-stremlit:0.0.1
    container_name: czsc-stremlit_1
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  czsc-stremlit_2:
    image: czsc-stremlit:0.0.1
    container_name: czsc-stremlit_2
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  czsc-stremlit_3:
    image: czsc-stremlit:0.0.1
    container_name: czsc-stremlit_3
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "8500:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - czsc-stremlit_1
      - czsc-stremlit_2
      - czsc-stremlit_3

volumes:
  data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/data/czsc_stremlit-data'
  streamlit-config-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/data/czsc_stremlit-config'